apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    k8s-app: influx
    version: v4
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: influx
    version: v4
  template:
    metadata:
      labels:
        k8s-app: influx
        version: v4
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: kubernetes/heapster_influxdb:v0.6
          name: influxdb
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - containerPort: 8083
            - containerPort: 8086
          volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: /data
      volumes:
      - name: influxdb-persistent-storage
        glusterfs:
          endpoints: glusterfs
          path: influxdb
          readOnly: false
